server:
  port: 8086

dubbo:
  registry:
    address: zookeeper://192.168.9.128:2181
  application:
    name: ego_order

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    cluster:
      nodes: 192.168.9.130:7001,192.168.9.130:7002,192.168.9.130:7003,192.168.9.130:7004,192.168.9.130:7005,192.168.9.130:7006





mylogin:
  cookie:
    name: TT_TOKEN

passport:
  url:
    showLogin: http://localhost:8084/user/showLogin


cart:
  usercart: cart