spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  data:
    solr:
      zk-host: 192.168.9.131:2181,192.168.9.131:2182,192.168.9.131:2183

mysolr:
  collection: collection1
dubbo:
  registry:
    address: zookeeper://192.168.9.128:2181
  application:
    name: ego_search
server:
  port: 8083
